In [1]:
# create matrix

In [2]:
x1 <- c(1,2,3)
x2 <- c(5,3,0)
x3 <- c(-1,7,3)
rbind(x1,x2,x3)

[,1] [,2] [,3]
x1  1   2    3   
x2  5   3    0   
x3 -1   7    3

In [3]:
# rowsum

mat <- matrix(1:9, nrow=3, byrow=T)
mat

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [4]:
rowSums(mat)

[1]  6 15 24

In [5]:
colSums(mat)

[1] 12 15 18

In [6]:
# rowmeans, col means
rowMeans(mat)

[1] 2 5 8

In [7]:
colMeans(mat)

[1] 4 5 6

In [8]:
# giving names to a matrix after creating

rownames(mat)<-c("A","B","C")
colnames(mat)<-c("D","E","F")
mat

D E F
A 1 2 3
B 4 5 6
C 7 8 9

In [9]:
# addition, subtraction
A <- matrix(c(10, 8,5, 12), ncol = 2, byrow = TRUE)
A

[,1] [,2]
[1,] 10    8  
[2,]  5   12

In [10]:
B <- matrix(c(5, 3,15, 6), ncol = 2, byrow = TRUE)
B

[,1] [,2]
[1,]  5   3   
[2,] 15   6

In [11]:
A + B

[,1] [,2]
[1,] 15   11  
[2,] 20   18

In [12]:
A - B

[,1] [,2]
[1,]   5  5   
[2,] -10  6

In [13]:
# transpose

In [14]:
t(A)

[,1] [,2]
[1,] 10    5  
[2,]  8   12

In [15]:
# scalar multiplication

In [16]:
2 * A

[,1] [,2]
[1,] 20   16  
[2,] 10   24

In [17]:
# elementwise multiplication (note: this is not matrix multiplication)

In [18]:
A * B

[,1] [,2]
[1,] 50   24  
[2,] 75   72

In [19]:
print(A)
print(B)

     [,1] [,2]
[1,]   10    8
[2,]    5   12
     [,1] [,2]
[1,]    5    3
[2,]   15    6


In [20]:
A %*% B

[,1] [,2]
[1,] 170  78  
[2,] 205  87

In [21]:
# determinant

In [22]:
det(B)

[1] -15

In [23]:
det(A)

[1] 80

In [24]:
# inverse of matrix

In [25]:
solve(A)

[,1]    [,2]  
[1,]  0.1500 -0.100
[2,] -0.0625  0.125

In [26]:
A %*% solve(A)

[,1]         [,2]
[1,] 1.000000e+00 0   
[2,] 1.110223e-16 1

In [27]:
# get the diagonal

In [28]:
mat <- cbind(x1,x2,x3)
mat

x1 x2 x3
[1,] 1  5  -1
[2,] 2  3   7
[3,] 3  0   3

In [29]:
diag(mat)

[1] 1 3 3

In [30]:
# create a matrix with a given diagonal

In [31]:
diag(c(7, 9, 2))

[,1] [,2] [,3]
[1,] 7    0    0   
[2,] 0    9    0   
[3,] 0    0    2

In [32]:
# create identity matrix of a given order

In [33]:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [34]:
# get eigen values and vectors

In [35]:
A = matrix(c(7,3,3,-1), nrow=2)
A

[,1] [,2]
[1,] 7     3  
[2,] 3    -1

In [36]:
eigen(A)

eigen() decomposition
$values
[1]  8 -2

$vectors
           [,1]       [,2]
[1,] -0.9486833  0.3162278
[2,] -0.3162278 -0.9486833


In [37]:
eigen(A)$values

[1]  8 -2

In [38]:
eigen(A)$vectors

[,1]       [,2]      
[1,] -0.9486833  0.3162278
[2,] -0.3162278 -0.9486833

In [39]:
install.packages("Matrix")


  There is a binary version available but the source version is later:
       binary source needs_compilation
Matrix  1.3-3  1.5-4              TRUE

  Binaries will be installed
package 'Matrix' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ssridhar\AppData\Local\Temp\Rtmpwv3VIe\downloaded_packages


In [40]:
library(Matrix)

Warning message:
"package 'Matrix' was built under R version 3.6.3"

In [65]:
matrix(1:9, nrow=3, byrow=F)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [41]:
A = matrix(1:9, nrow=3, byrow=T)
l <- lu(A)

In [42]:
expand(l)$P %*% expand(l)$L %*% expand(l)$U

3 x 3 Matrix of class "dgeMatrix"
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

In [43]:
example(lu)


lu> ##--- Dense  -------------------------
lu> x <- Matrix(rnorm(9), 3, 3)

lu> lu(x)
'MatrixFactorization' of Formal class 'denseLU' [package "Matrix"] with 4 slots
  ..@ x       : num [1:9] -0.285 0.517 -0.751 1.308 -2.165 ...
  ..@ perm    : int [1:3] 1 3 3
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ Dim     : int [1:2] 3 3

lu> dim(x2 <- round(10 * x[,-3]))# non-square
[1] 3 2

lu> expand(lu2 <- lu(x2))
$L
3 x 2 Matrix of class "dgeMatrix"
           [,1]        [,2]
[1,]  1.0000000  0.00000000
[2,]  0.3333333  1.00000000
[3,] -0.6666667 -0.03448276

$U
2 x 2 Matrix of class "dtrMatrix"
     [,1]      [,2]     
[1,]  -3.00000  13.00000
[2,]         . -19.33333

$P
3 x 3 sparse Matrix of class "pMatrix"
          
[1,] | . .
[2,] . . |
[3,] . | .


lu> ##--- Sparse (see more in ?"sparseLU-class")----- % ./sparseLU-class.Rd
lu> 
lu> pm <- as(readMM(system.file("external/pores_1.mtx",
lu+                             package = "Matrix")),
lu+          "CsparseMatrix

In [44]:
install.packages("matrixcalc")


  There is a binary version available but the source version is later:
           binary source needs_compilation
matrixcalc  1.0-3  1.0-6             FALSE



installing the source package 'matrixcalc'



In [45]:
library(matrixcalc)

In [46]:
lu.decomposition(A)

$L
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    4    1    0
[3,]    7    2    1

$U
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    0   -3   -6
[3,]    0    0    0

In [47]:
luA <- lu.decomposition(A)
L <- luA$L
U <- luA$U

In [48]:
L %*% U

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [49]:
mat <- matrix(1:9, nrow=3,byrow=T)
mat

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [50]:
# Exercises

In [51]:
# create a 5x5 matrix

In [52]:
# subset a row

In [53]:
# subset a column

In [54]:
# subset some rows and cols

In [55]:
# calculate the sum of rows

In [56]:
# calculate the sum of cols

In [57]:
# check the dimensions of the matrix

In [58]:
# is this matrix invertible?

In [59]:
# invert the matrix

In [60]:
# get the eigen value and vectors

In [61]:
# verify fo all eigen vectors v is if Av = <lambda> v

In [ ]:
# learn about Singular Value Decomposition and try that using a library
# try to achieve the same using eigen() function and compare reaults